// flow-typed signature: 03fcaf015dd23cd9fb1b3056ce7b7c09
// flow-typed version: <<STUB>>/D_v^1.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'D'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'D' {
  declare module.exports: any;
}
