// flow-typed signature: f4adfc82e9766ee3a3e9f5e58f0d15bb
// flow-typed version: <<STUB>>/D_v^1.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'D'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'D' {
  declare module.exports: any;
}
