// flow-typed signature: 6228dffc6b8078463634ecab3eac8cf0
// flow-typed version: <<STUB>>/eslint-plugin-xss_v^0.1.9/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-xss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-xss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-xss/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-xss/lib/re' {
  declare module.exports: any;
}

declare module 'eslint-plugin-xss/lib/Rules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-xss/lib/rules/no-location-href-assign' {
  declare module.exports: any;
}

declare module 'eslint-plugin-xss/lib/rules/no-mixed-html' {
  declare module.exports: any;
}

declare module 'eslint-plugin-xss/lib/tree' {
  declare module.exports: any;
}

declare module 'eslint-plugin-xss/tests/lib/rules/no-location-href-assign' {
  declare module.exports: any;
}

declare module 'eslint-plugin-xss/tests/lib/rules/no-mixed-html' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-xss/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-xss/lib/index'>;
}
declare module 'eslint-plugin-xss/lib/re.js' {
  declare module.exports: $Exports<'eslint-plugin-xss/lib/re'>;
}
declare module 'eslint-plugin-xss/lib/Rules.js' {
  declare module.exports: $Exports<'eslint-plugin-xss/lib/Rules'>;
}
declare module 'eslint-plugin-xss/lib/rules/no-location-href-assign.js' {
  declare module.exports: $Exports<'eslint-plugin-xss/lib/rules/no-location-href-assign'>;
}
declare module 'eslint-plugin-xss/lib/rules/no-mixed-html.js' {
  declare module.exports: $Exports<'eslint-plugin-xss/lib/rules/no-mixed-html'>;
}
declare module 'eslint-plugin-xss/lib/tree.js' {
  declare module.exports: $Exports<'eslint-plugin-xss/lib/tree'>;
}
declare module 'eslint-plugin-xss/tests/lib/rules/no-location-href-assign.js' {
  declare module.exports: $Exports<'eslint-plugin-xss/tests/lib/rules/no-location-href-assign'>;
}
declare module 'eslint-plugin-xss/tests/lib/rules/no-mixed-html.js' {
  declare module.exports: $Exports<'eslint-plugin-xss/tests/lib/rules/no-mixed-html'>;
}
